### ISSUE TITLE
Selecting a suite should look in all categories

### ISSUE THREAD

**Issue by carlosmn** [clar-test/clar#27]
If you run `./libgit2_clar -s49` where that suite is part of the "network" category, it won't find it unless you also add `-iall` or `-inetwork`. If I know which suite I want to run explicitly, it shouldn't matter which category it's in. As the while suite belongs in one category, it's not like I can use it to run suite 49 except for the network tests.

So I think `-s` should imply `-iall` internally. I might take a stab later, for now I'm just complaining.

**Comment by ethomson** [comment]
Agree that this is outdated, closing.
